// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	uuid "github.com/google/uuid"
)

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	CreatedAt string
	UpdatedAt string
	ExpiresAt string
	RevokedAt sql.NullString
}

type Transaction struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Amount     float64
	Currency   string
	Category   sql.NullString
	Note       sql.NullString
	OccurredAt string
	CreatedAt  string
	UpdatedAt  string
}

type User struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Password  string
	CreatedAt string
	UpdatedAt string
}
