// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	uuid "github.com/google/uuid"
)

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Transaction struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Amount     float64
	Currency   string
	Category   sql.NullString
	Note       sql.NullString
	OccurredAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
