// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	uuid "github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, user_id, amount, currency, category, note, occurred_at, created_at, updated_at)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, amount, currency, category, note, occurred_at, created_at, updated_at
`

type CreateTransactionParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Amount     float64
	Currency   string
	Category   sql.NullString
	Note       sql.NullString
	OccurredAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Category,
		arg.Note,
		arg.OccurredAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.Note,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT id, user_id, amount, currency, category, note, occurred_at, created_at, updated_at FROM transactions 
WHERE user_id = ?
ORDER BY occurred_at DESC
LIMIT ? OFFSET ?
`

type ListTransactionsByUserParams struct {
	UserID uuid.UUID
	Limit  int64
	Offset int64
}

func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.Note,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumByDay = `-- name: SumByDay :many
SELECT date(occurred_at) AS day, SUM(amount) AS total
FROM TRANSACTIONS 
WHERE user_id = ? AND occurred_at BETWEEN ? AND ?
GROUP BY day
ORDER BY day
`

type SumByDayRow struct {
	Day   interface{}
	Total sql.NullFloat64
}

func (q *Queries) SumByDay(ctx context.Context, userID uuid.UUID) ([]SumByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, sumByDay, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumByDayRow
	for rows.Next() {
		var i SumByDayRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumByMonth = `-- name: SumByMonth :many
SELECT strftime('%Y-%m', occurred_at) AS month, SUM(amount) AS total
from transactions
where user_id = ? AND occurred_at BETWEEN ? AND ?
GROUP BY month
ORDER BY month
`

type SumByMonthRow struct {
	Month interface{}
	Total sql.NullFloat64
}

func (q *Queries) SumByMonth(ctx context.Context, userID uuid.UUID) ([]SumByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, sumByMonth, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumByMonthRow
	for rows.Next() {
		var i SumByMonthRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumByYear = `-- name: SumByYear :many
SELECT strftime('%Y', occurred_at) AS year, SUM(amount) AS total
FROM transactions
WHERE user_id = ? AND occurred_at BETWEEN ? AND ?
GROUP BY year
ORDER BY year
`

type SumByYearRow struct {
	Year  interface{}
	Total sql.NullFloat64
}

func (q *Queries) SumByYear(ctx context.Context, userID uuid.UUID) ([]SumByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, sumByYear, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumByYearRow
	for rows.Next() {
		var i SumByYearRow
		if err := rows.Scan(&i.Year, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
