// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package db

import (
	"context"
	"database/sql"

	uuid "github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id,
    user_id,
    amount,
    currency,
    category,
    note,
    occurred_at,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, amount, currency, category, note, occurred_at, created_at, updated_at
`

type CreateTransactionParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Amount     float64
	Currency   string
	Category   sql.NullString
	Note       sql.NullString
	OccurredAt string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Category,
		arg.Note,
		arg.OccurredAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.Note,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT
    id,
    user_id,
    amount,
    currency,
    category,
    note,
    occurred_at,
    created_at,
    updated_at
FROM transactions
WHERE user_id = ?
ORDER BY occurred_at DESC
LIMIT ? OFFSET ?
`

type ListTransactionsByUserParams struct {
	UserID uuid.UUID
	Limit  int64
	Offset int64
}

func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.Note,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
